name: C/C++ module CI with CMake and Ninja

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build

    - name: Install Software to manage repositories
      run: sudo apt-get install -y software-properties-common lsb-release wget

    - name: Add LLVM gpg key
      run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -


    - name: Add LLVM repository
      run: sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-18 main"

    - name: Update Package lists
      run: sudo apt-get update


    - name: Update clang
      run: sudo apt-get install clang-18

    - name: set clang 18 as default
      run: sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100

    - name: Update to ninja 1.11.1
      run: sudo wget https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-linux.zip && sudo unzip ninja-linux.zip -d /usr/local/bin/

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja

    - name: Build
      run: cmake --build build

    - name: Test
      run: ./build/module_test
